#!/usr/bin/env bash

function clamp {
  min=$1
  max=$2
  val=$3
  python -c "print(max($min, min($max, $val)))"
}

direction=$1
current=$2

if [ "$direction" = "down" ]; then
  target=$(clamp 1 10 $(($current + 1)))
  i3-msg workspace number $target
elif [ "$direction" = "up" ]; then
  target=$(clamp 1 10 $(($current - 1)))
  i3-msg workspace number $target
fi 